destination: ./dev
excerpt_separator: <!--more-->
exclude: ["scss/"]
future: true
paginate: 5
paginate_path: "/blog/page:num/"
permalink: /blog/:categories/:title.html
gems: [jekyll-paginate]
source: ./src
defaults:
  -
    scope:
      path: ""
    values:
      layout: "main"